name: lookalike-finder
dependencies:
- python==3.10.0
- pillow--9.2.0
- scipy==1.9.0
- pandas==1.4.3
- pip==20.3.4
- pip:
    - cmake==3.23.3
    - dlib==19.24.0
    - face_recognition==1.3.0
    - opencv-python==4.4.0.66
    - matplotlib==3.5.3
    - pre-commit==1.21.0
    - tqdm==4.64.0