name: lookalike_finder
dependencies:
- python==3.5.2
- pillow==5.0.0
- scipy==1.1.0
- pandas==0.23.4
- pip==20.3.4
- pip:
    - cmake==3.23.3
    - dlib==19.24.0
    - face_recognition==1.3.0
    - opencv-python==4.4.0.42
    - matplotlib==3.0.3
    - pre-commit==1.21.0
    - tqdm==4.64.0